# Generated by Django 2.2.3 on 2019-08-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersalary',
            name='create_time',
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='month',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='income',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentpaid',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
