# Generated by Django 2.2.3 on 2019-09-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190824_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
