# Generated by Django 2.2.3 on 2019-09-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190901_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentpaid',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
